#!/bin/bash

RPCV="$(sudo -Hiu root env | grep '^PATH' | cut -d= -f2)"
echo "$RPCV" | grep -q "::" && echo -e "root's path contains a empty directory (::)\n"
echo "$RPCV" | grep -q ":$" && echo -e "root's path contains a trailing (:)\n"

for x in $(echo "$RPCV" | tr ":" " ")
do
  if [ -d "$x" ]
  then
    ls -ldH "$x" | awk '$9 == "." {print "PATH contains current working directory (.)\n"} 
    $3 != "root" {print $9, "is not owned by root\n"}
    substr($1,6,1) != "-" {print $9, "is group writable\n"}
    substr($1,9,1) != "-" {print $9, "is world writable\n"}'
  else
    echo "$x is not a directory"
  fi
done